// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://orgbsbthfitvsrgpazas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZ2JzYnRoZml0dnNyZ3BhemFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk5MTUwMzcsImV4cCI6MjA1NTQ5MTAzN30.tHpWx1cjqREzVsSo_QB5MAO1CevIaLvxMJnc3UPHIVI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);